version: '3.3'
services:
  pg:
    container_name: lesson2
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: password
  redis:
    container_name: redis-test2
    image: redis
    ports:
      - "6385:6379"
    volumes:
      - db_data:/var/lib/redis
volumes:
  db_data: { }