spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6385}
  datasource:
    url: jdbc:postgresql://localhost:5432/technest10
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update